---
- name: Start Droplet
  digital_ocean:
    api_token: "{{do_api_token}}"
    state: active
    command: droplet
    id: "{{dev_droplet_id}}"
  register: droplet_info
- set_fact:
    droplet_ip: "{{droplet_info.droplet.ip_address}}"